apiVersion: v1
kind: Pod
metadata:
  name: kip
  namespace: default
spec:
  containers:
  - image: gcr.io/aviv-playground/kip
    imagePullPolicy: Always
    name: kip

  restartPolicy: Always

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kip-rbac
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: default
    # Reference to upper's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io